### ISSUE TITLE
How to Setup?

### ISSUE THREAD

**Issue by comod** [Digital-Alchemy-TS/core#135]
Hi!
I don't understand how to set up this app.
The documentation at https://docs.digital-alchemy.app/docs/core doesn't explain how to configure a tsconfig or package.json scripts to get started.

Is there an example app available?

**Comment by comod** [comment]
jsut found https://github.com/Digital-Alchemy-TS/standalone-template

**Comment by zoe-codez** [comment]
Haha, where did you come in from? I can drop a more obvious link there
