### ISSUE TITLE
Logs display in 12-hr time with no AM/PM

### ISSUE THREAD

**Issue by allout58** [Digital-Alchemy-TS/core#63]
https://github.com/Digital-Alchemy-TS/core/blob/ffd339915a936165ea45fe09ac8b74a70dab2ecf/src/extensions/logger.extension.ts#L136

The logs are in 12 hour time (`hh`) rather than 24 hour time as I believe the intent is (`HH`) . 

https://day.js.org/docs/en/display/format#list-of-all-available-formats

**Comment by zoe-codez** [comment]
😅  I sorta like that, format, but it's probably not the best default. The PR will make it configurable, and change the default to be 24h

**Comment by zoe-codez** [comment]
Updated with `v24.9.1`
